services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduma
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: eduma
      DB_USERNAME: root
      DB_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduma
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

  wordpress:
    image: wordpress:6.5-php8.2-apache
    container_name: wordpress
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: laravel
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - laravel
  
  eduma-n8n:   
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678
      - N8N_CORS_ALLOW_ORIGIN=http://localhost:8000
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: eduma
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
      - app
    restart: always
    networks:
      - laravel
    command: php artisan schedule:work

volumes:
  dbdata:
  wordpress_data:

networks:
  laravel:
    driver: bridge